# Generated by Django 3.0.3 on 2020-02-24 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subcategoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao_subcategoria', models.CharField(blank=True, max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao_categoria', models.TextField(unique=True, verbose_name='categoria')),
                ('subcategoria', models.ManyToManyField(blank=True, to='despesa.Subcategoria')),
            ],
        ),
    ]
