# Generated by Django 3.0.3 on 2020-03-02 16:50

from django.db import migrations, models
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('despesa', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='despesa',
            old_name='categoria',
            new_name='categorias',
        ),
        migrations.RemoveField(
            model_name='despesa',
            name='subcategoria',
        ),
        migrations.AddField(
            model_name='categoria',
            name='subcategorias',
            field=models.ManyToManyField(blank=True, to='despesa.Subcategoria'),
        ),
        migrations.AddField(
            model_name='despesa',
            name='subcategorias',
            field=smart_selects.db_fields.ChainedManyToManyField(chained_field='categoria', chained_model_field='categoria', horizontal=True, to='despesa.Subcategoria', verbose_name='subcategorias'),
        ),
        migrations.AlterModelTable(
            name='categoria',
            table='categoria',
        ),
        migrations.AlterModelTable(
            name='despesa',
            table='despesa',
        ),
        migrations.AlterModelTable(
            name='subcategoria',
            table='subcategoria',
        ),
        migrations.AlterModelTable(
            name='tipodocumento',
            table='tipoDocumento',
        ),
        migrations.AlterModelTable(
            name='tipotransacao',
            table='tipoTransacao',
        ),
    ]
