# Generated by Django 3.0.3 on 2020-02-24 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('despesa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(max_length=50)),
                ('complemento', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TipoTransacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_transacao', models.CharField(max_length=50)),
                ('complemento', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Despesa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('data_despesa', models.DateField(verbose_name='data')),
                ('valor_despesa', models.FloatField(verbose_name='valor')),
                ('descricao_despesa', models.TextField(max_length=255)),
                ('documento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='despesa.TipoDocumento')),
                ('transacao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='despesa.TipoTransacao')),
            ],
        ),
    ]
