# Generated by Django 3.0.3 on 2020-02-24 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('despesa', '0002_despesa_tipodocumento_tipotransacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despesa',
            name='valor_despesa',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
