# Generated by Django 3.0.3 on 2020-03-02 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('despesa', '0003_auto_20200302_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despesa',
            name='documento',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='despesa.TipoDocumento'),
        ),
        migrations.RemoveField(
            model_name='despesa',
            name='subcategorias',
        ),
        migrations.AddField(
            model_name='despesa',
            name='subcategorias',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='subcategorias', related_query_name='subcategorias', to='despesa.Subcategoria'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='despesa',
            name='transacao',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='despesa.TipoTransacao'),
        ),
    ]
