# Generated by Django 3.0.3 on 2020-02-26 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('despesa', '0003_auto_20200224_1730'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipodocumento',
            name='complemento',
        ),
        migrations.RemoveField(
            model_name='tipotransacao',
            name='complemento',
        ),
        migrations.AddField(
            model_name='despesa',
            name='documento_complemento',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='despesa',
            name='transacao_complemento',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
