# Generated by Django 3.0.3 on 2020-03-02 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('despesa', '0004_auto_20200302_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='descricao_categoria',
            field=models.CharField(default=None, max_length=254, unique=True, verbose_name='categoria'),
        ),
        migrations.AlterField(
            model_name='despesa',
            name='subcategorias',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='despesa.Subcategoria'),
        ),
    ]
