# Generated by Django 3.0.3 on 2020-03-03 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('despesa', '0005_auto_20200302_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='despesa',
            name='conciliado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='despesa',
            name='categorias',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='despesa.Categoria'),
        ),
        migrations.AlterField(
            model_name='despesa',
            name='documento',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='despesa.TipoDocumento'),
        ),
        migrations.AlterField(
            model_name='despesa',
            name='transacao',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='despesa.TipoTransacao'),
        ),
        migrations.AlterField(
            model_name='despesa',
            name='valor_despesa',
            field=models.FloatField(max_length=10),
        ),
    ]
