# Generated by Django 3.0.3 on 2020-02-24 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_auto_20200204_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cpf',
            field=models.TextField(default=0, max_length=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='telefone',
            field=models.TextField(default=11000000000000, max_length=12),
            preserve_default=False,
        ),
    ]
