# Generated by Django 3.0.3 on 2020-02-24 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='status',
            old_name='Status',
            new_name='status',
        ),
    ]
