# Generated by Django 3.0.3 on 2020-02-24 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_auto_20200224_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cpf',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='profile',
            name='telefone',
            field=models.CharField(max_length=12),
        ),
    ]
