# Generated by Django 3.0.3 on 2020-02-24 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_auto_20200224_1220'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Status',
        ),
    ]
